In [52]:
import pandas as pd 
import numpy as np

In [53]:
df = pd.read_csv(r"c:\Users\Mr.user\Downloads\diabetes (1).csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [54]:
df.corr()[['Outcome']]

                           Outcome
Pregnancies               0.221898
Glucose                   0.466581
BloodPressure             0.065068
SkinThickness             0.074752
Insulin                   0.130548
BMI                       0.292695
DiabetesPedigreeFunction  0.173844
Age                       0.238356
Outcome                   1.000000

In [55]:
X  = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [56]:
from sklearn.preprocessing import StandardScaler

In [57]:
scaler = StandardScaler()

X = scaler.fit_transform(X)
X

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]], shape=(768, 8))

In [58]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [59]:
import tensorflow 
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [60]:
model = Sequential()
model.add(Dense(16, activation='relu',input_dim=8))
model.add(Dense(1, activation='sigmoid'))

c:\Users\Mr.user\anaconda3\envs\ml\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [61]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [62]:
model.fit(X_train, y_train, batch_size=32, epochs=100, validation_split=0.2)

Epoch 1/100

16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.5703 - loss: 0.6962 - val_accuracy: 0.5854 - val_loss: 0.6983
Epoch 2/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5866 - loss: 0.6601 - val_accuracy: 0.5854 - val_loss: 0.6670
Epoch 3/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6232 - loss: 0.6294 - val_accuracy: 0.6016 - val_loss: 0.6367
Epoch 4/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6517 - loss: 0.6032 - val_accuracy: 0.6260 - val_loss: 0.6119
Epoch 5/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6721 - loss: 0.5817 - val_accuracy: 0.6829 - val_loss: 0.5896
Epoch 6/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6986 - loss: 0.5627 - val_accuracy: 0.6829 - val_loss: 0.5727
Epoch 7/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7169 - loss: 0.5467 - val_accuracy: 0.6992 - val_loss: 0.5575
Epoch 8/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7291 - loss: 0.5334 - val_accuracy: 0.7073 - val_loss: 0.5466
Epoch 9/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7454 - loss: 0.5215 - val_accuracy: 0.7073 - val_loss: 0.5343
Epoch 10/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7515 - loss: 0.5117 - val_accuracy: 0.7154 - val_loss: 0.5232
Epoch 11/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7576 - loss: 0.5028 - val_accuracy: 0.7154 - val_loss: 0.5148
Epoch 12/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7637 - loss: 0.4949 - val_accuracy: 0.7398 - val_loss: 0.5055
Epoch 13/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7617 - loss: 0.4884 - val_accuracy: 0.7317 - val_loss: 0.4997
Epoch 14/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7637 - loss: 0.4821 - val_accuracy: 0.7317 - val_loss: 0.4932
Epoch 15/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7637 - loss: 0.4772 - val_accuracy: 0.7398 - val_loss: 0.4894
Epoch 16/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7678 - loss: 0.4725 - val_accuracy: 0.7398 - val_loss: 0.4855
Epoch 17/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7678 - loss: 0.4693 - val_accuracy: 0.7398 - val_loss: 0.4837
Epoch 18/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7637 - loss: 0.4657 - val_accuracy: 0.7480 - val_loss: 0.4803
Epoch 19/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7637 - loss: 0.4627 - val_accuracy: 0.7398 - val_loss: 0.4780
Epoch 20/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7699 - loss: 0.4595 - val_accuracy: 0.7480 - val_loss: 0.4761
Epoch 21/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7739 - loss: 0.4570 - val_accuracy: 0.7480 - val_loss: 0.4740
Epoch 22/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7780 - loss: 0.4548 - val_accuracy: 0.7561 - val_loss: 0.4735
Epoch 23/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7821 - loss: 0.4526 - val_accuracy: 0.7561 - val_loss: 0.4710
Epoch 24/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7862 - loss: 0.4505 - val_accuracy: 0.7480 - val_loss: 0.4689
Epoch 25/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7902 - loss: 0.4488 - val_accuracy: 0.7480 - val_loss: 0.4679
Epoch 26/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7882 - loss: 0.4472 - val_accuracy: 0.7480 - val_loss: 0.4667
Epoch 27/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7923 - loss: 0.4454 - val_accuracy: 0.7561 - val_loss: 0.4656
Epoch 28/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7923 - loss: 0.4443 - val_accuracy: 0.7561 - val_loss: 0.4649
Epoch 29/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7943 - loss: 0.4433 - val_accuracy: 0.7642 - val_loss: 0.4658
Epoch 30/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7902 - loss: 0.4414 - val_accuracy: 0.7561 - val_loss: 0.4642
Epoch 31/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7923 - loss: 0.4404 - val_accuracy: 0.7642 - val_loss: 0.4638
Epoch 32/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7923 - loss: 0.4391 - val_accuracy: 0.7642 - val_loss: 0.4628
Epoch 33/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7902 - loss: 0.4378 - val_accuracy: 0.7642 - val_loss: 0.4623
Epoch 34/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7902 - loss: 0.4369 - val_accuracy: 0.7642 - val_loss: 0.4619
Epoch 35/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7923 - loss: 0.4362 - val_accuracy: 0.7724 - val_loss: 0.4614
Epoch 36/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7923 - loss: 0.4347 - val_accuracy: 0.7724 - val_loss: 0.4606
Epoch 37/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7943 - loss: 0.4340 - val_accuracy: 0.7724 - val_loss: 0.4610
Epoch 38/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7923 - loss: 0.4331 - val_accuracy: 0.7724 - val_loss: 0.4609
Epoch 39/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7902 - loss: 0.4324 - val_accuracy: 0.7724 - val_loss: 0.4603
Epoch 40/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7862 - loss: 0.4320 - val_accuracy: 0.7724 - val_loss: 0.4609
Epoch 41/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7902 - loss: 0.4307 - val_accuracy: 0.7724 - val_loss: 0.4604
Epoch 42/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7923 - loss: 0.4301 - val_accuracy: 0.7724 - val_loss: 0.4606
Epoch 43/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7943 - loss: 0.4293 - val_accuracy: 0.7724 - val_loss: 0.4610
Epoch 44/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7943 - loss: 0.4290 - val_accuracy: 0.7724 - val_loss: 0.4625
Epoch 45/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7963 - loss: 0.4279 - val_accuracy: 0.7642 - val_loss: 0.4616
Epoch 46/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7984 - loss: 0.4275 - val_accuracy: 0.7642 - val_loss: 0.4615
Epoch 47/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7963 - loss: 0.4266 - val_accuracy: 0.7642 - val_loss: 0.4615
Epoch 48/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7943 - loss: 0.4257 - val_accuracy: 0.7642 - val_loss: 0.4613
Epoch 49/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7963 - loss: 0.4253 - val_accuracy: 0.7642 - val_loss: 0.4611
Epoch 50/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7963 - loss: 0.4247 - val_accuracy: 0.7642 - val_loss: 0.4620
Epoch 51/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7963 - loss: 0.4242 - val_accuracy: 0.7642 - val_loss: 0.4621
Epoch 52/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7943 - loss: 0.4239 - val_accuracy: 0.7724 - val_loss: 0.4620
Epoch 53/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7943 - loss: 0.4231 - val_accuracy: 0.7724 - val_loss: 0.4615
Epoch 54/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7963 - loss: 0.4222 - val_accuracy: 0.7642 - val_loss: 0.4626
Epoch 55/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7943 - loss: 0.4217 - val_accuracy: 0.7642 - val_loss: 0.4629
Epoch 56/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7984 - loss: 0.4215 - val_accuracy: 0.7724 - val_loss: 0.4632
Epoch 57/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7963 - loss: 0.4211 - val_accuracy: 0.7642 - val_loss: 0.4626
Epoch 58/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7984 - loss: 0.4202 - val_accuracy: 0.7724 - val_loss: 0.4628
Epoch 59/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8004 - loss: 0.4198 - val_accuracy: 0.7724 - val_loss: 0.4636
Epoch 60/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7943 - loss: 0.4196 - val_accuracy: 0.7642 - val_loss: 0.4627
Epoch 61/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7984 - loss: 0.4187 - val_accuracy: 0.7642 - val_loss: 0.4633
Epoch 62/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8024 - loss: 0.4182 - val_accuracy: 0.7642 - val_loss: 0.4641
Epoch 63/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7943 - loss: 0.4180 - val_accuracy: 0.7642 - val_loss: 0.4648
Epoch 64/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7943 - loss: 0.4170 - val_accuracy: 0.7642 - val_loss: 0.4653
Epoch 65/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8004 - loss: 0.4172 - val_accuracy: 0.7642 - val_loss: 0.4645
Epoch 66/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7984 - loss: 0.4162 - val_accuracy: 0.7642 - val_loss: 0.4649
Epoch 67/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7963 - loss: 0.4159 - val_accuracy: 0.7642 - val_loss: 0.4648
Epoch 68/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7984 - loss: 0.4155 - val_accuracy: 0.7642 - val_loss: 0.4651
Epoch 69/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7984 - loss: 0.4150 - val_accuracy: 0.7642 - val_loss: 0.4658
Epoch 70/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7984 - loss: 0.4142 - val_accuracy: 0.7642 - val_loss: 0.4661
Epoch 71/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7963 - loss: 0.4140 - val_accuracy: 0.7642 - val_loss: 0.4659
Epoch 72/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8004 - loss: 0.4134 - val_accuracy: 0.7642 - val_loss: 0.4669
Epoch 73/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8004 - loss: 0.4134 - val_accuracy: 0.7642 - val_loss: 0.4663
Epoch 74/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7984 - loss: 0.4128 - val_accuracy: 0.7642 - val_loss: 0.4674
Epoch 75/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7943 - loss: 0.4124 - val_accuracy: 0.7642 - val_loss: 0.4666
Epoch 76/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7963 - loss: 0.4120 - val_accuracy: 0.7642 - val_loss: 0.4674
Epoch 77/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7984 - loss: 0.4117 - val_accuracy: 0.7642 - val_loss: 0.4674
Epoch 78/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8024 - loss: 0.4114 - val_accuracy: 0.7642 - val_loss: 0.4667
Epoch 79/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8004 - loss: 0.4110 - val_accuracy: 0.7642 - val_loss: 0.4675
Epoch 80/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8004 - loss: 0.4104 - val_accuracy: 0.7561 - val_loss: 0.4686
Epoch 81/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8106 - loss: 0.4104 - val_accuracy: 0.7561 - val_loss: 0.4684
Epoch 82/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8065 - loss: 0.4099 - val_accuracy: 0.7561 - val_loss: 0.4679
Epoch 83/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7984 - loss: 0.4100 - val_accuracy: 0.7642 - val_loss: 0.4683
Epoch 84/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8024 - loss: 0.4093 - val_accuracy: 0.7561 - val_loss: 0.4685
Epoch 85/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8045 - loss: 0.4089 - val_accuracy: 0.7642 - val_loss: 0.4681
Epoch 86/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8045 - loss: 0.4084 - val_accuracy: 0.7561 - val_loss: 0.4681
Epoch 87/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8045 - loss: 0.4081 - val_accuracy: 0.7642 - val_loss: 0.4681
Epoch 88/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8024 - loss: 0.4076 - val_accuracy: 0.7642 - val_loss: 0.4681
Epoch 89/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8065 - loss: 0.4074 - val_accuracy: 0.7642 - val_loss: 0.4684
Epoch 90/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8045 - loss: 0.4074 - val_accuracy: 0.7642 - val_loss: 0.4685
Epoch 91/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8065 - loss: 0.4070 - val_accuracy: 0.7642 - val_loss: 0.4683
Epoch 92/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8045 - loss: 0.4068 - val_accuracy: 0.7642 - val_loss: 0.4690
Epoch 93/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8024 - loss: 0.4064 - val_accuracy: 0.7642 - val_loss: 0.4693
Epoch 94/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8045 - loss: 0.4061 - val_accuracy: 0.7642 - val_loss: 0.4691
Epoch 95/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8086 - loss: 0.4057 - val_accuracy: 0.7642 - val_loss: 0.4695
Epoch 96/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8086 - loss: 0.4053 - val_accuracy: 0.7642 - val_loss: 0.4696
Epoch 97/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8106 - loss: 0.4051 - val_accuracy: 0.7724 - val_loss: 0.4700
Epoch 98/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8086 - loss: 0.4048 - val_accuracy: 0.7724 - val_loss: 0.4704
Epoch 99/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8086 - loss: 0.4047 - val_accuracy: 0.7724 - val_loss: 0.4706
Epoch 100/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8045 - loss: 0.4045 - val_accuracy: 0.7724 - val_loss: 0.4698

How to select an appropriate optimizer
How to determine the number of nodes in each layer
How to select the appropriate number of layers
How to use all these concepts together in a single model

How to select an appropriate optimizer

In [63]:
import kerastuner as kt

In [64]:
def build_model(hp):
    model = Sequential()
    model.add(Dense(32, activation='relu', input_dim=8))
    model.add(Dense(1, activation='sigmoid'))
    
    model.compile(optimizer=hp.Choice('optimizer',values =['adam', 'rmsprop', 'sgd','adadelta']), loss='binary_crossentropy', metrics=['accuracy'])
    return model

How tuner objects makes

In [65]:
tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=5
)

Reloading Tuner from .\untitled_project\tuner0.json

In [66]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

In [67]:
tune

NameError: name 'tune' is not defined

We can also abstract your model

In [ ]:
model = tuner.get_best_models(num_models=1)[0]
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(X_train, y_train, epochs=100, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7850 - loss: 0.4303 - val_accuracy: 0.7597 - val_loss: 0.5143
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7866 - loss: 0.4301 - val_accuracy: 0.7597 - val_loss: 0.5149
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7866 - loss: 0.4299 - val_accuracy: 0.7597 - val_loss: 0.5151
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7866 - loss: 0.4297 - val_accuracy: 0.7597 - val_loss: 0.5152
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4295 - val_accuracy: 0.7597 - val_loss: 0.5153
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4293 - val_accuracy: 0.7597 - val_loss: 0.5155
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4290 - val_accuracy: 0.7597 - val_loss: 0.5155
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7866 - loss: 0.4289 - val_accuracy: 0.7597 - val_loss: 0.5155
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4288 - val_accuracy: 0.7597 - val_loss: 0.5155
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7883 - loss: 0.4285 - val_accuracy: 0.7597 - val_loss: 0.5153
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7883 - loss: 0.4283 - val_accuracy: 0.7662 - val_loss: 0.5168
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7899 - loss: 0.4282 - val_accuracy: 0.7662 - val_loss: 0.5166
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7899 - loss: 0.4279 - val_accuracy: 0.7662 - val_loss: 0.5168
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7899 - loss: 0.4277 - val_accuracy: 0.7662 - val_loss: 0.5175
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7915 - loss: 0.4276 - val_accuracy: 0.7597 - val_loss: 0.5171
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4274 - val_accuracy: 0.7662 - val_loss: 0.5162
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7883 - loss: 0.4272 - val_accuracy: 0.7662 - val_loss: 0.5164
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7866 - loss: 0.4270 - val_accuracy: 0.7662 - val_loss: 0.5164
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7915 - loss: 0.4268 - val_accuracy: 0.7662 - val_loss: 0.5165
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7883 - loss: 0.4267 - val_accuracy: 0.7662 - val_loss: 0.5163
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7883 - loss: 0.4265 - val_accuracy: 0.7662 - val_loss: 0.5163
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7866 - loss: 0.4263 - val_accuracy: 0.7662 - val_loss: 0.5165
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7883 - loss: 0.4262 - val_accuracy: 0.7662 - val_loss: 0.5170
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7899 - loss: 0.4259 - val_accuracy: 0.7662 - val_loss: 0.5171
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4256 - val_accuracy: 0.7662 - val_loss: 0.5170
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7899 - loss: 0.4256 - val_accuracy: 0.7662 - val_loss: 0.5174
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7915 - loss: 0.4254 - val_accuracy: 0.7662 - val_loss: 0.5172
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7883 - loss: 0.4252 - val_accuracy: 0.7662 - val_loss: 0.5175
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7899 - loss: 0.4250 - val_accuracy: 0.7662 - val_loss: 0.5171
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7899 - loss: 0.4249 - val_accuracy: 0.7662 - val_loss: 0.5174
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7899 - loss: 0.4248 - val_accuracy: 0.7662 - val_loss: 0.5176
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7915 - loss: 0.4246 - val_accuracy: 0.7662 - val_loss: 0.5179
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7932 - loss: 0.4244 - val_accuracy: 0.7662 - val_loss: 0.5181
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4245 - val_accuracy: 0.7662 - val_loss: 0.5179
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7948 - loss: 0.4241 - val_accuracy: 0.7662 - val_loss: 0.5181
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7948 - loss: 0.4241 - val_accuracy: 0.7662 - val_loss: 0.5186
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7964 - loss: 0.4239 - val_accuracy: 0.7662 - val_loss: 0.5192
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7932 - loss: 0.4237 - val_accuracy: 0.7662 - val_loss: 0.5196
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4235 - val_accuracy: 0.7662 - val_loss: 0.5196
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7932 - loss: 0.4234 - val_accuracy: 0.7662 - val_loss: 0.5198
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7948 - loss: 0.4231 - val_accuracy: 0.7662 - val_loss: 0.5202
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7948 - loss: 0.4230 - val_accuracy: 0.7662 - val_loss: 0.5201
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7964 - loss: 0.4229 - val_accuracy: 0.7662 - val_loss: 0.5203
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7964 - loss: 0.4227 - val_accuracy: 0.7662 - val_loss: 0.5204
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7932 - loss: 0.4226 - val_accuracy: 0.7597 - val_loss: 0.5207
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7866 - loss: 0.4225 - val_accuracy: 0.7662 - val_loss: 0.5202
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4224 - val_accuracy: 0.7662 - val_loss: 0.5207
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7915 - loss: 0.4222 - val_accuracy: 0.7662 - val_loss: 0.5206
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7948 - loss: 0.4221 - val_accuracy: 0.7662 - val_loss: 0.5208
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7964 - loss: 0.4219 - val_accuracy: 0.7662 - val_loss: 0.5213
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7915 - loss: 0.4218 - val_accuracy: 0.7662 - val_loss: 0.5212
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7980 - loss: 0.4217 - val_accuracy: 0.7662 - val_loss: 0.5212
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7932 - loss: 0.4216 - val_accuracy: 0.7662 - val_loss: 0.5217
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7964 - loss: 0.4214 - val_accuracy: 0.7662 - val_loss: 0.5218
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7948 - loss: 0.4212 - val_accuracy: 0.7662 - val_loss: 0.5219
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7915 - loss: 0.4211 - val_accuracy: 0.7662 - val_loss: 0.5221
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7932 - loss: 0.4209 - val_accuracy: 0.7662 - val_loss: 0.5221
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7964 - loss: 0.4209 - val_accuracy: 0.7662 - val_loss: 0.5217
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7948 - loss: 0.4207 - val_accuracy: 0.7662 - val_loss: 0.5216
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4206 - val_accuracy: 0.7662 - val_loss: 0.5214
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7997 - loss: 0.4205 - val_accuracy: 0.7662 - val_loss: 0.5207
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7997 - loss: 0.4203 - val_accuracy: 0.7662 - val_loss: 0.5210
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4203 - val_accuracy: 0.7597 - val_loss: 0.5205
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7964 - loss: 0.4201 - val_accuracy: 0.7597 - val_loss: 0.5202
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7980 - loss: 0.4201 - val_accuracy: 0.7597 - val_loss: 0.5198
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7980 - loss: 0.4200 - val_accuracy: 0.7597 - val_loss: 0.5200
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7964 - loss: 0.4199 - val_accuracy: 0.7597 - val_loss: 0.5203
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7997 - loss: 0.4197 - val_accuracy: 0.7597 - val_loss: 0.5205
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7997 - loss: 0.4195 - val_accuracy: 0.7662 - val_loss: 0.5204
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7997 - loss: 0.4195 - val_accuracy: 0.7727 - val_loss: 0.5204
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7980 - loss: 0.4193 - val_accuracy: 0.7727 - val_loss: 0.5198
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4191 - val_accuracy: 0.7662 - val_loss: 0.5199
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4191 - val_accuracy: 0.7727 - val_loss: 0.5200
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4189 - val_accuracy: 0.7727 - val_loss: 0.5200
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4188 - val_accuracy: 0.7662 - val_loss: 0.5202
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7980 - loss: 0.4187 - val_accuracy: 0.7662 - val_loss: 0.5203
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7980 - loss: 0.4185 - val_accuracy: 0.7727 - val_loss: 0.5199
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4185 - val_accuracy: 0.7727 - val_loss: 0.5196
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7980 - loss: 0.4184 - val_accuracy: 0.7727 - val_loss: 0.5198
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7964 - loss: 0.4183 - val_accuracy: 0.7727 - val_loss: 0.5199
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7980 - loss: 0.4181 - val_accuracy: 0.7727 - val_loss: 0.5200
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7964 - loss: 0.4181 - val_accuracy: 0.7662 - val_loss: 0.5207
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4179 - val_accuracy: 0.7727 - val_loss: 0.5211
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7964 - loss: 0.4178 - val_accuracy: 0.7662 - val_loss: 0.5206
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7964 - loss: 0.4177 - val_accuracy: 0.7662 - val_loss: 0.5205
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7964 - loss: 0.4176 - val_accuracy: 0.7727 - val_loss: 0.5202
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4176 - val_accuracy: 0.7662 - val_loss: 0.5209
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7980 - loss: 0.4174 - val_accuracy: 0.7727 - val_loss: 0.5216
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4172 - val_accuracy: 0.7727 - val_loss: 0.5222
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7997 - loss: 0.4173 - val_accuracy: 0.7727 - val_loss: 0.5222
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7980 - loss: 0.4170 - val_accuracy: 0.7727 - val_loss: 0.5225
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7980 - loss: 0.4170 - val_accuracy: 0.7727 - val_loss: 0.5229
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7964 - loss: 0.4169 - val_accuracy: 0.7727 - val_loss: 0.5224
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7964 - loss: 0.4169 - val_accuracy: 0.7727 - val_loss: 0.5227
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7997 - loss: 0.4167 - val_accuracy: 0.7727 - val_loss: 0.5228
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4167 - val_accuracy: 0.7727 - val_loss: 0.5219
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7964 - loss: 0.4164 - val_accuracy: 0.7727 - val_loss: 0.5218
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7964 - loss: 0.4164 - val_accuracy: 0.7597 - val_loss: 0.5216
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4163 - val_accuracy: 0.7662 - val_loss: 0.5216
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7980 - loss: 0.4161 - val_accuracy: 0.7662 - val_loss: 0.5208

How to determine the number of nodes in each layer

In [ ]:
def build_model(hp):
    model = Sequential()
    units = hp.Int('unit',8, 128, step=8) 
    model.add(Dense(units= units, activation='relu',input_dim=8))
    model.add(Dense(1, activation='sigmoid'))
    model.compile(optimizer= 'rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
tuner.search(X_train, y_train, epochs=50,validation_data=(X_test, y_test))

In [ ]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'sgd'}

In [ ]:
model = tuner.get_best_models(num_models=1)[0]

c:\Users\Mr.user\anaconda3\envs\ml\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.fit(X_train, y_train,batch_size=32, epochs=100, validation_data=(X_test, y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.7134 - loss: 0.6245 - val_accuracy: 0.7078 - val_loss: 0.6220
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7280 - loss: 0.6070 - val_accuracy: 0.6948 - val_loss: 0.6076
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7345 - loss: 0.5919 - val_accuracy: 0.6818 - val_loss: 0.5954
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7362 - loss: 0.5789 - val_accuracy: 0.6948 - val_loss: 0.5860
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7394 - loss: 0.5680 - val_accuracy: 0.7013 - val_loss: 0.5774
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7476 - loss: 0.5583 - val_accuracy: 0.7078 - val_loss: 0.5700
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7508 - loss: 0.5498 - val_accuracy: 0.7208 - val_loss: 0.5635
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7541 - loss: 0.5418 - val_accuracy: 0.7273 - val_loss: 0.5579
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7557 - loss: 0.5350 - val_accuracy: 0.7273 - val_loss: 0.5531
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7541 - loss: 0.5286 - val_accuracy: 0.7338 - val_loss: 0.5486
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.5231 - val_accuracy: 0.7338 - val_loss: 0.5455
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7557 - loss: 0.5183 - val_accuracy: 0.7403 - val_loss: 0.5430
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.5138 - val_accuracy: 0.7532 - val_loss: 0.5396
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7573 - loss: 0.5095 - val_accuracy: 0.7597 - val_loss: 0.5366
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7606 - loss: 0.5056 - val_accuracy: 0.7662 - val_loss: 0.5341
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7638 - loss: 0.5018 - val_accuracy: 0.7597 - val_loss: 0.5316
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7638 - loss: 0.4983 - val_accuracy: 0.7662 - val_loss: 0.5303
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7655 - loss: 0.4956 - val_accuracy: 0.7597 - val_loss: 0.5285
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7655 - loss: 0.4926 - val_accuracy: 0.7597 - val_loss: 0.5275
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4898 - val_accuracy: 0.7597 - val_loss: 0.5256
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.4874 - val_accuracy: 0.7597 - val_loss: 0.5240
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4847 - val_accuracy: 0.7597 - val_loss: 0.5228
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4827 - val_accuracy: 0.7597 - val_loss: 0.5214
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4806 - val_accuracy: 0.7662 - val_loss: 0.5200
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4786 - val_accuracy: 0.7662 - val_loss: 0.5192
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4767 - val_accuracy: 0.7727 - val_loss: 0.5176
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4748 - val_accuracy: 0.7662 - val_loss: 0.5166
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4733 - val_accuracy: 0.7662 - val_loss: 0.5158
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7801 - loss: 0.4716 - val_accuracy: 0.7792 - val_loss: 0.5150
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4699 - val_accuracy: 0.7727 - val_loss: 0.5145
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4685 - val_accuracy: 0.7792 - val_loss: 0.5141
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4670 - val_accuracy: 0.7792 - val_loss: 0.5136
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4657 - val_accuracy: 0.7792 - val_loss: 0.5127
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4644 - val_accuracy: 0.7792 - val_loss: 0.5124
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4632 - val_accuracy: 0.7792 - val_loss: 0.5123
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7834 - loss: 0.4620 - val_accuracy: 0.7792 - val_loss: 0.5120
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4607 - val_accuracy: 0.7792 - val_loss: 0.5119
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4598 - val_accuracy: 0.7792 - val_loss: 0.5116
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4588 - val_accuracy: 0.7792 - val_loss: 0.5113
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4579 - val_accuracy: 0.7662 - val_loss: 0.5103
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4568 - val_accuracy: 0.7662 - val_loss: 0.5105
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4559 - val_accuracy: 0.7532 - val_loss: 0.5102
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4550 - val_accuracy: 0.7468 - val_loss: 0.5105
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4539 - val_accuracy: 0.7532 - val_loss: 0.5106
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4530 - val_accuracy: 0.7532 - val_loss: 0.5095
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4522 - val_accuracy: 0.7532 - val_loss: 0.5094
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4515 - val_accuracy: 0.7532 - val_loss: 0.5098
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4509 - val_accuracy: 0.7532 - val_loss: 0.5101
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4501 - val_accuracy: 0.7532 - val_loss: 0.5103
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4494 - val_accuracy: 0.7597 - val_loss: 0.5105
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4487 - val_accuracy: 0.7597 - val_loss: 0.5100
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4482 - val_accuracy: 0.7597 - val_loss: 0.5103
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4477 - val_accuracy: 0.7597 - val_loss: 0.5100
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4470 - val_accuracy: 0.7662 - val_loss: 0.5100
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4465 - val_accuracy: 0.7597 - val_loss: 0.5106
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4458 - val_accuracy: 0.7597 - val_loss: 0.5105
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4452 - val_accuracy: 0.7662 - val_loss: 0.5112
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4447 - val_accuracy: 0.7662 - val_loss: 0.5111
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4442 - val_accuracy: 0.7597 - val_loss: 0.5107
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4437 - val_accuracy: 0.7597 - val_loss: 0.5107
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4433 - val_accuracy: 0.7597 - val_loss: 0.5106
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4428 - val_accuracy: 0.7597 - val_loss: 0.5107
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4422 - val_accuracy: 0.7532 - val_loss: 0.5110
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4419 - val_accuracy: 0.7532 - val_loss: 0.5117
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4414 - val_accuracy: 0.7532 - val_loss: 0.5124
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4409 - val_accuracy: 0.7532 - val_loss: 0.5125
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4404 - val_accuracy: 0.7532 - val_loss: 0.5128
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4401 - val_accuracy: 0.7532 - val_loss: 0.5120
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4397 - val_accuracy: 0.7532 - val_loss: 0.5122
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7850 - loss: 0.4392 - val_accuracy: 0.7532 - val_loss: 0.5121
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7866 - loss: 0.4389 - val_accuracy: 0.7468 - val_loss: 0.5114
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4384 - val_accuracy: 0.7468 - val_loss: 0.5112
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4381 - val_accuracy: 0.7468 - val_loss: 0.5111
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4377 - val_accuracy: 0.7468 - val_loss: 0.5110
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4373 - val_accuracy: 0.7532 - val_loss: 0.5113
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4371 - val_accuracy: 0.7468 - val_loss: 0.5112
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4368 - val_accuracy: 0.7468 - val_loss: 0.5117
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4365 - val_accuracy: 0.7468 - val_loss: 0.5118
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4361 - val_accuracy: 0.7468 - val_loss: 0.5123
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4358 - val_accuracy: 0.7532 - val_loss: 0.5124
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4354 - val_accuracy: 0.7597 - val_loss: 0.5128
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4352 - val_accuracy: 0.7597 - val_loss: 0.5129
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4349 - val_accuracy: 0.7597 - val_loss: 0.5131
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4345 - val_accuracy: 0.7597 - val_loss: 0.5131
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4343 - val_accuracy: 0.7597 - val_loss: 0.5133
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7850 - loss: 0.4341 - val_accuracy: 0.7532 - val_loss: 0.5134
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7834 - loss: 0.4338 - val_accuracy: 0.7532 - val_loss: 0.5134
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4336 - val_accuracy: 0.7532 - val_loss: 0.5134
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4331 - val_accuracy: 0.7532 - val_loss: 0.5137
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4329 - val_accuracy: 0.7597 - val_loss: 0.5153
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4328 - val_accuracy: 0.7597 - val_loss: 0.5148
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4325 - val_accuracy: 0.7597 - val_loss: 0.5149
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4322 - val_accuracy: 0.7597 - val_loss: 0.5144
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4319 - val_accuracy: 0.7597 - val_loss: 0.5141
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4317 - val_accuracy: 0.7597 - val_loss: 0.5146
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4315 - val_accuracy: 0.7597 - val_loss: 0.5146
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4313 - val_accuracy: 0.7597 - val_loss: 0.5148
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4311 - val_accuracy: 0.7597 - val_loss: 0.5152
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4308 - val_accuracy: 0.7597 - val_loss: 0.5158
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4306 - val_accuracy: 0.7597 - val_loss: 0.5176

How to select the appropriate number of layers

In [ ]:
def build_model(hp):
    model = Sequential()
    model.add(Dense(72, activation='relu', input_dim=8))
    for i in range(hp.Int('number of layers',1, 10)):
        model.add(Dense(72, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])
    return model

In [ ]:
tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=3,
    directory='my_dir',
    project_name='num_layers'
)

c:\Users\Mr.user\anaconda3\envs\ml\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test, y_test))
data = (X_test,y_test)
tuner.get_best_hyperparameters()[0].values
model = tuner.get_best_models(num_models=1)[0]
model.fit(X_train, y_train, epochs=100,initial_epoch=6, validation_data=(X_test,y_test))

Epoch 7/100

c:\Users\Mr.user\anaconda3\envs\ml\lib\site-packages\keras\src\saving\saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 20 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.7671 - loss: 0.4717 - val_accuracy: 0.7338 - val_loss: 0.5286
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4540 - val_accuracy: 0.7273 - val_loss: 0.5412
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4382 - val_accuracy: 0.6753 - val_loss: 0.5828
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4299 - val_accuracy: 0.7208 - val_loss: 0.5466
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4169 - val_accuracy: 0.7727 - val_loss: 0.5654
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4067 - val_accuracy: 0.7273 - val_loss: 0.5860
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.3975 - val_accuracy: 0.7597 - val_loss: 0.6172
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.3957 - val_accuracy: 0.7273 - val_loss: 0.5959
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.3725 - val_accuracy: 0.6883 - val_loss: 0.6335
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8339 - loss: 0.3667 - val_accuracy: 0.6948 - val_loss: 0.6208
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3567 - val_accuracy: 0.6818 - val_loss: 0.6258
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8436 - loss: 0.3367 - val_accuracy: 0.6688 - val_loss: 0.6772
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8567 - loss: 0.3208 - val_accuracy: 0.7013 - val_loss: 0.8676
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8469 - loss: 0.3307 - val_accuracy: 0.6818 - val_loss: 0.6754
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8681 - loss: 0.2985 - val_accuracy: 0.7143 - val_loss: 0.8088
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8567 - loss: 0.3168 - val_accuracy: 0.7143 - val_loss: 0.7290
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8811 - loss: 0.2774 - val_accuracy: 0.7143 - val_loss: 0.8323
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8958 - loss: 0.2680 - val_accuracy: 0.6948 - val_loss: 0.9329
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8811 - loss: 0.2526 - val_accuracy: 0.6948 - val_loss: 1.0412
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8795 - loss: 0.2730 - val_accuracy: 0.6753 - val_loss: 0.8667
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9007 - loss: 0.2393 - val_accuracy: 0.6753 - val_loss: 0.9359
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9104 - loss: 0.2226 - val_accuracy: 0.7208 - val_loss: 0.9315
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9072 - loss: 0.2493 - val_accuracy: 0.6948 - val_loss: 0.9760
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9283 - loss: 0.1942 - val_accuracy: 0.6883 - val_loss: 1.2117
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9218 - loss: 0.2002 - val_accuracy: 0.7273 - val_loss: 1.0715
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9218 - loss: 0.1915 - val_accuracy: 0.7273 - val_loss: 1.1230
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9365 - loss: 0.1787 - val_accuracy: 0.6688 - val_loss: 1.3476
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9463 - loss: 0.1579 - val_accuracy: 0.6494 - val_loss: 1.3031
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9397 - loss: 0.1653 - val_accuracy: 0.6818 - val_loss: 1.2119
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9577 - loss: 0.1281 - val_accuracy: 0.6364 - val_loss: 1.7150
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9463 - loss: 0.1561 - val_accuracy: 0.7013 - val_loss: 1.3950
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9430 - loss: 0.1369 - val_accuracy: 0.7013 - val_loss: 1.3951
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9381 - loss: 0.1775 - val_accuracy: 0.7208 - val_loss: 1.3109
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9625 - loss: 0.1227 - val_accuracy: 0.6429 - val_loss: 1.5262
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9723 - loss: 0.0775 - val_accuracy: 0.6753 - val_loss: 1.7395
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9658 - loss: 0.1102 - val_accuracy: 0.6818 - val_loss: 1.7298
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9642 - loss: 0.0996 - val_accuracy: 0.6494 - val_loss: 1.7989
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9528 - loss: 0.1430 - val_accuracy: 0.6494 - val_loss: 1.7326
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9674 - loss: 0.1106 - val_accuracy: 0.6623 - val_loss: 1.6567
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9723 - loss: 0.0781 - val_accuracy: 0.6948 - val_loss: 1.8944
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9625 - loss: 0.1136 - val_accuracy: 0.6688 - val_loss: 1.8521
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9772 - loss: 0.0692 - val_accuracy: 0.7013 - val_loss: 1.8621
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9674 - loss: 0.0920 - val_accuracy: 0.6429 - val_loss: 2.1731
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9560 - loss: 0.1239 - val_accuracy: 0.6558 - val_loss: 1.8639
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9821 - loss: 0.0516 - val_accuracy: 0.6623 - val_loss: 2.0716
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9756 - loss: 0.0618 - val_accuracy: 0.6753 - val_loss: 2.1355
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9788 - loss: 0.0550 - val_accuracy: 0.6883 - val_loss: 2.1791
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9772 - loss: 0.0562 - val_accuracy: 0.6623 - val_loss: 2.4028
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9674 - loss: 0.0871 - val_accuracy: 0.6558 - val_loss: 2.1593
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9853 - loss: 0.0424 - val_accuracy: 0.6558 - val_loss: 2.3096
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9902 - loss: 0.0389 - val_accuracy: 0.6364 - val_loss: 2.4950
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9821 - loss: 0.0619 - val_accuracy: 0.6948 - val_loss: 2.1688
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9772 - loss: 0.0714 - val_accuracy: 0.6429 - val_loss: 2.6717
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9870 - loss: 0.0463 - val_accuracy: 0.6429 - val_loss: 2.4608
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0083 - val_accuracy: 0.6429 - val_loss: 2.8404
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9886 - loss: 0.0316 - val_accuracy: 0.6429 - val_loss: 2.4617
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9805 - loss: 0.0555 - val_accuracy: 0.6753 - val_loss: 2.4043
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9805 - loss: 0.0475 - val_accuracy: 0.6429 - val_loss: 2.5553
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9919 - loss: 0.0309 - val_accuracy: 0.6753 - val_loss: 2.8901
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9837 - loss: 0.0703 - val_accuracy: 0.6688 - val_loss: 2.7325
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9805 - loss: 0.0802 - val_accuracy: 0.6364 - val_loss: 2.3223
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9967 - loss: 0.0124 - val_accuracy: 0.6623 - val_loss: 2.9976
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9772 - loss: 0.0783 - val_accuracy: 0.6818 - val_loss: 2.4936
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9870 - loss: 0.0301 - val_accuracy: 0.6558 - val_loss: 2.7377
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9870 - loss: 0.0485 - val_accuracy: 0.6753 - val_loss: 2.5699
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0199 - val_accuracy: 0.6818 - val_loss: 2.7979
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0406 - val_accuracy: 0.6558 - val_loss: 2.9296
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9870 - loss: 0.0346 - val_accuracy: 0.6558 - val_loss: 2.9219
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0235 - val_accuracy: 0.5974 - val_loss: 3.1844
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9919 - loss: 0.0222 - val_accuracy: 0.6948 - val_loss: 3.1113
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9984 - loss: 0.0094 - val_accuracy: 0.6883 - val_loss: 3.5143
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9788 - loss: 0.0785 - val_accuracy: 0.6169 - val_loss: 2.8973
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9886 - loss: 0.0426 - val_accuracy: 0.6818 - val_loss: 2.6233
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0029 - val_accuracy: 0.6818 - val_loss: 3.0703
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 9.7785e-04 - val_accuracy: 0.6818 - val_loss: 3.5272
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 3.5407e-04 - val_accuracy: 0.6688 - val_loss: 3.9283
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 1.4635e-04 - val_accuracy: 0.6753 - val_loss: 4.2482
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9560 - loss: 0.2147 - val_accuracy: 0.6688 - val_loss: 3.5818
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0040 - val_accuracy: 0.6753 - val_loss: 3.5850
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9984 - loss: 0.0026 - val_accuracy: 0.6688 - val_loss: 3.5466
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 4.1081e-04 - val_accuracy: 0.6883 - val_loss: 3.7916
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9674 - loss: 0.1181 - val_accuracy: 0.6558 - val_loss: 3.1544
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9951 - loss: 0.0121 - val_accuracy: 0.6688 - val_loss: 3.2399
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0010 - val_accuracy: 0.6558 - val_loss: 3.5969
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 4.4398e-04 - val_accuracy: 0.6623 - val_loss: 3.8342
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 2.1176e-04 - val_accuracy: 0.6688 - val_loss: 4.1274
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 1.0285e-04 - val_accuracy: 0.6688 - val_loss: 4.3588
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9723 - loss: 0.1364 - val_accuracy: 0.6169 - val_loss: 3.5669
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9853 - loss: 0.0327 - val_accuracy: 0.6558 - val_loss: 3.5512
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9870 - loss: 0.0494 - val_accuracy: 0.6299 - val_loss: 3.0636
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9886 - loss: 0.0364 - val_accuracy: 0.6299 - val_loss: 2.9638
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0017 - val_accuracy: 0.6688 - val_loss: 3.2379
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 6.2944e-04 - val_accuracy: 0.6429 - val_loss: 3.5198
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 2.7642e-04 - val_accuracy: 0.6558 - val_loss: 3.8472

How to use all these concepts together in a single model

In [ ]:
def build_model(hp):
    model = Sequential()
    for i in range(hp.Int('number of layers', 1, 10)):
        if i == 0:
            model.add(Dense(hp.Int('units'+str(i),8,128,step=8), activation=hp.choice('activation'+str(i), values=['relu', 'tanh', 'sigmoid']), input_dim=8))
        else:
            model.add(Dense(hp.Int('units'+str(i),8,128,step=8), activation=hp.choice('activation'+str(i), values=['relu', 'tanh', 'sigmoid'])))
    i +=1

In [ ]:
model.add(Dense(1, activation = 'sigmoid' ))

In [ ]:
model.compile(optimizer=hp.Choice('optimizer',values =['adam', 'rmsprop', 'sgd','adadelta']), loss='binary_crossentropy', metrics=['accuracy'])
return model

NameError: name 'hp' is not defined

In [68]:
tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=3,
    directory='my_dir',
    project_name='num_layers'
)

Reloading Tuner from my_dir\num_layers\tuner0.json

In [69]:
tuner.search(X_train,y_train,epochs=5, validation_data=(X_test, y_test))

In [70]:
tuner.get_best_hyperparameters()[0].values

{'number of layers': 7}

In [73]:
model.fit(X_train, y_train, epochs=200, initial_epoch=6, validation_data=(X_test,y_test))

Epoch 7/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8029 - loss: 0.4179 - val_accuracy: 0.7597 - val_loss: 0.5551
Epoch 8/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4169 - val_accuracy: 0.7662 - val_loss: 0.5540
Epoch 9/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7980 - loss: 0.4164 - val_accuracy: 0.7662 - val_loss: 0.5538
Epoch 10/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7997 - loss: 0.4158 - val_accuracy: 0.7662 - val_loss: 0.5514
Epoch 11/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7980 - loss: 0.4151 - val_accuracy: 0.7727 - val_loss: 0.5504
Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4145 - val_accuracy: 0.7727 - val_loss: 0.5508
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8029 - loss: 0.4143 - val_accuracy: 0.7727 - val_loss: 0.5505
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4142 - val_accuracy: 0.7662 - val_loss: 0.5491
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8062 - loss: 0.4134 - val_accuracy: 0.7597 - val_loss: 0.5496
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8062 - loss: 0.4130 - val_accuracy: 0.7727 - val_loss: 0.5483
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4127 - val_accuracy: 0.7597 - val_loss: 0.5495
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4124 - val_accuracy: 0.7597 - val_loss: 0.5508
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.4122 - val_accuracy: 0.7597 - val_loss: 0.5501
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8111 - loss: 0.4119 - val_accuracy: 0.7727 - val_loss: 0.5491
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8127 - loss: 0.4109 - val_accuracy: 0.7662 - val_loss: 0.5485
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8127 - loss: 0.4110 - val_accuracy: 0.7532 - val_loss: 0.5506
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8143 - loss: 0.4110 - val_accuracy: 0.7532 - val_loss: 0.5510
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8094 - loss: 0.4106 - val_accuracy: 0.7532 - val_loss: 0.5494
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8127 - loss: 0.4100 - val_accuracy: 0.7597 - val_loss: 0.5497
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8127 - loss: 0.4095 - val_accuracy: 0.7597 - val_loss: 0.5509
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8176 - loss: 0.4098 - val_accuracy: 0.7532 - val_loss: 0.5518
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8160 - loss: 0.4091 - val_accuracy: 0.7597 - val_loss: 0.5515
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8143 - loss: 0.4088 - val_accuracy: 0.7597 - val_loss: 0.5520
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8127 - loss: 0.4086 - val_accuracy: 0.7597 - val_loss: 0.5521
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8127 - loss: 0.4081 - val_accuracy: 0.7597 - val_loss: 0.5528
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8176 - loss: 0.4082 - val_accuracy: 0.7597 - val_loss: 0.5530
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8127 - loss: 0.4083 - val_accuracy: 0.7532 - val_loss: 0.5531
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8176 - loss: 0.4080 - val_accuracy: 0.7532 - val_loss: 0.5573
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8160 - loss: 0.4074 - val_accuracy: 0.7597 - val_loss: 0.5550
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8160 - loss: 0.4071 - val_accuracy: 0.7597 - val_loss: 0.5563
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8143 - loss: 0.4067 - val_accuracy: 0.7597 - val_loss: 0.5550
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.4069 - val_accuracy: 0.7597 - val_loss: 0.5540
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8160 - loss: 0.4064 - val_accuracy: 0.7597 - val_loss: 0.5542
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8143 - loss: 0.4062 - val_accuracy: 0.7597 - val_loss: 0.5545
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8111 - loss: 0.4068 - val_accuracy: 0.7468 - val_loss: 0.5525
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8192 - loss: 0.4058 - val_accuracy: 0.7403 - val_loss: 0.5538
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8160 - loss: 0.4053 - val_accuracy: 0.7403 - val_loss: 0.5533
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8111 - loss: 0.4054 - val_accuracy: 0.7403 - val_loss: 0.5543
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8143 - loss: 0.4050 - val_accuracy: 0.7532 - val_loss: 0.5547
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8127 - loss: 0.4049 - val_accuracy: 0.7468 - val_loss: 0.5560
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8127 - loss: 0.4045 - val_accuracy: 0.7468 - val_loss: 0.5557
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8160 - loss: 0.4040 - val_accuracy: 0.7532 - val_loss: 0.5545
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8111 - loss: 0.4038 - val_accuracy: 0.7468 - val_loss: 0.5550
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8127 - loss: 0.4038 - val_accuracy: 0.7532 - val_loss: 0.5554
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8176 - loss: 0.4038 - val_accuracy: 0.7468 - val_loss: 0.5578
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8160 - loss: 0.4031 - val_accuracy: 0.7403 - val_loss: 0.5582
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8192 - loss: 0.4026 - val_accuracy: 0.7468 - val_loss: 0.5572
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8160 - loss: 0.4024 - val_accuracy: 0.7468 - val_loss: 0.5578
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8176 - loss: 0.4023 - val_accuracy: 0.7403 - val_loss: 0.5583
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8143 - loss: 0.4021 - val_accuracy: 0.7468 - val_loss: 0.5576
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8176 - loss: 0.4021 - val_accuracy: 0.7403 - val_loss: 0.5577
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8176 - loss: 0.4016 - val_accuracy: 0.7468 - val_loss: 0.5578
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8176 - loss: 0.4012 - val_accuracy: 0.7468 - val_loss: 0.5570
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8127 - loss: 0.4015 - val_accuracy: 0.7468 - val_loss: 0.5571
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8160 - loss: 0.4008 - val_accuracy: 0.7403 - val_loss: 0.5568
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8176 - loss: 0.4013 - val_accuracy: 0.7403 - val_loss: 0.5598
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8176 - loss: 0.4010 - val_accuracy: 0.7403 - val_loss: 0.5613
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8160 - loss: 0.4002 - val_accuracy: 0.7403 - val_loss: 0.5619
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8176 - loss: 0.4001 - val_accuracy: 0.7468 - val_loss: 0.5616
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8176 - loss: 0.4000 - val_accuracy: 0.7403 - val_loss: 0.5613
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8176 - loss: 0.3994 - val_accuracy: 0.7403 - val_loss: 0.5588
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8160 - loss: 0.3991 - val_accuracy: 0.7468 - val_loss: 0.5609
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8160 - loss: 0.3990 - val_accuracy: 0.7468 - val_loss: 0.5615
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8176 - loss: 0.3987 - val_accuracy: 0.7468 - val_loss: 0.5607
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8176 - loss: 0.3983 - val_accuracy: 0.7403 - val_loss: 0.5612
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8176 - loss: 0.3980 - val_accuracy: 0.7403 - val_loss: 0.5614
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8127 - loss: 0.3986 - val_accuracy: 0.7403 - val_loss: 0.5621
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.3979 - val_accuracy: 0.7468 - val_loss: 0.5629
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8176 - loss: 0.3976 - val_accuracy: 0.7468 - val_loss: 0.5621
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8160 - loss: 0.3978 - val_accuracy: 0.7468 - val_loss: 0.5641
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8160 - loss: 0.3968 - val_accuracy: 0.7403 - val_loss: 0.5652
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8143 - loss: 0.3970 - val_accuracy: 0.7468 - val_loss: 0.5653
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8127 - loss: 0.3969 - val_accuracy: 0.7468 - val_loss: 0.5634
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8127 - loss: 0.3964 - val_accuracy: 0.7468 - val_loss: 0.5630
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8143 - loss: 0.3966 - val_accuracy: 0.7468 - val_loss: 0.5641
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8127 - loss: 0.3959 - val_accuracy: 0.7468 - val_loss: 0.5629
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8127 - loss: 0.3961 - val_accuracy: 0.7532 - val_loss: 0.5653
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8111 - loss: 0.3960 - val_accuracy: 0.7532 - val_loss: 0.5642
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8127 - loss: 0.3954 - val_accuracy: 0.7468 - val_loss: 0.5644
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8127 - loss: 0.3962 - val_accuracy: 0.7468 - val_loss: 0.5637
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8143 - loss: 0.3953 - val_accuracy: 0.7403 - val_loss: 0.5658
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8127 - loss: 0.3951 - val_accuracy: 0.7468 - val_loss: 0.5667
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8127 - loss: 0.3945 - val_accuracy: 0.7532 - val_loss: 0.5658
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8127 - loss: 0.3946 - val_accuracy: 0.7468 - val_loss: 0.5645
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8143 - loss: 0.3945 - val_accuracy: 0.7532 - val_loss: 0.5658
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8127 - loss: 0.3942 - val_accuracy: 0.7532 - val_loss: 0.5632
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8143 - loss: 0.3940 - val_accuracy: 0.7468 - val_loss: 0.5608
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8127 - loss: 0.3940 - val_accuracy: 0.7468 - val_loss: 0.5627
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8160 - loss: 0.3932 - val_accuracy: 0.7468 - val_loss: 0.5629
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8160 - loss: 0.3930 - val_accuracy: 0.7532 - val_loss: 0.5600
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8176 - loss: 0.3928 - val_accuracy: 0.7532 - val_loss: 0.5613
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8192 - loss: 0.3929 - val_accuracy: 0.7532 - val_loss: 0.5613
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8160 - loss: 0.3927 - val_accuracy: 0.7468 - val_loss: 0.5625
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8160 - loss: 0.3925 - val_accuracy: 0.7468 - val_loss: 0.5632
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.3922 - val_accuracy: 0.7468 - val_loss: 0.5640
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8176 - loss: 0.3927 - val_accuracy: 0.7532 - val_loss: 0.5638
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8192 - loss: 0.3916 - val_accuracy: 0.7468 - val_loss: 0.5645
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8176 - loss: 0.3919 - val_accuracy: 0.7468 - val_loss: 0.5646
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8160 - loss: 0.3921 - val_accuracy: 0.7532 - val_loss: 0.5625
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8160 - loss: 0.3912 - val_accuracy: 0.7532 - val_loss: 0.5650
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8143 - loss: 0.3917 - val_accuracy: 0.7468 - val_loss: 0.5636
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8160 - loss: 0.3905 - val_accuracy: 0.7468 - val_loss: 0.5642
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8176 - loss: 0.3912 - val_accuracy: 0.7532 - val_loss: 0.5664
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8176 - loss: 0.3906 - val_accuracy: 0.7532 - val_loss: 0.5653
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.3904 - val_accuracy: 0.7468 - val_loss: 0.5651
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8160 - loss: 0.3900 - val_accuracy: 0.7532 - val_loss: 0.5658
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8176 - loss: 0.3903 - val_accuracy: 0.7532 - val_loss: 0.5640
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8176 - loss: 0.3897 - val_accuracy: 0.7532 - val_loss: 0.5665
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8143 - loss: 0.3894 - val_accuracy: 0.7468 - val_loss: 0.5649
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8176 - loss: 0.3898 - val_accuracy: 0.7532 - val_loss: 0.5648
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.3887 - val_accuracy: 0.7468 - val_loss: 0.5650
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8192 - loss: 0.3889 - val_accuracy: 0.7468 - val_loss: 0.5650
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8160 - loss: 0.3890 - val_accuracy: 0.7468 - val_loss: 0.5644
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8208 - loss: 0.3886 - val_accuracy: 0.7468 - val_loss: 0.5644
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8208 - loss: 0.3887 - val_accuracy: 0.7468 - val_loss: 0.5636
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8192 - loss: 0.3878 - val_accuracy: 0.7532 - val_loss: 0.5645
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.3878 - val_accuracy: 0.7532 - val_loss: 0.5652
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.3877 - val_accuracy: 0.7532 - val_loss: 0.5660
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8192 - loss: 0.3873 - val_accuracy: 0.7532 - val_loss: 0.5669
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8160 - loss: 0.3873 - val_accuracy: 0.7532 - val_loss: 0.5658
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8192 - loss: 0.3871 - val_accuracy: 0.7468 - val_loss: 0.5670
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8192 - loss: 0.3876 - val_accuracy: 0.7597 - val_loss: 0.5664
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.3874 - val_accuracy: 0.7468 - val_loss: 0.5691
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8192 - loss: 0.3863 - val_accuracy: 0.7532 - val_loss: 0.5694
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8225 - loss: 0.3864 - val_accuracy: 0.7468 - val_loss: 0.5692
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8208 - loss: 0.3861 - val_accuracy: 0.7597 - val_loss: 0.5690
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8192 - loss: 0.3864 - val_accuracy: 0.7532 - val_loss: 0.5695
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8208 - loss: 0.3853 - val_accuracy: 0.7532 - val_loss: 0.5689
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8257 - loss: 0.3857 - val_accuracy: 0.7532 - val_loss: 0.5665
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3855 - val_accuracy: 0.7532 - val_loss: 0.5697
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3852 - val_accuracy: 0.7532 - val_loss: 0.5694
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8241 - loss: 0.3851 - val_accuracy: 0.7468 - val_loss: 0.5701
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3850 - val_accuracy: 0.7468 - val_loss: 0.5691
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8241 - loss: 0.3847 - val_accuracy: 0.7532 - val_loss: 0.5693
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8257 - loss: 0.3845 - val_accuracy: 0.7597 - val_loss: 0.5696
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8225 - loss: 0.3846 - val_accuracy: 0.7597 - val_loss: 0.5691
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8225 - loss: 0.3842 - val_accuracy: 0.7597 - val_loss: 0.5716
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8257 - loss: 0.3837 - val_accuracy: 0.7597 - val_loss: 0.5726
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8257 - loss: 0.3835 - val_accuracy: 0.7597 - val_loss: 0.5718
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3834 - val_accuracy: 0.7597 - val_loss: 0.5715
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.3831 - val_accuracy: 0.7597 - val_loss: 0.5725
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8274 - loss: 0.3831 - val_accuracy: 0.7532 - val_loss: 0.5705
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8257 - loss: 0.3830 - val_accuracy: 0.7597 - val_loss: 0.5705
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.3828 - val_accuracy: 0.7597 - val_loss: 0.5717
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8241 - loss: 0.3830 - val_accuracy: 0.7532 - val_loss: 0.5721
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8225 - loss: 0.3828 - val_accuracy: 0.7597 - val_loss: 0.5737
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3825 - val_accuracy: 0.7532 - val_loss: 0.5733
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8274 - loss: 0.3826 - val_accuracy: 0.7532 - val_loss: 0.5755
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8241 - loss: 0.3822 - val_accuracy: 0.7532 - val_loss: 0.5730
Epoch 156/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8257 - loss: 0.3826 - val_accuracy: 0.7597 - val_loss: 0.5742
Epoch 157/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.3815 - val_accuracy: 0.7597 - val_loss: 0.5746
Epoch 158/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8257 - loss: 0.3822 - val_accuracy: 0.7597 - val_loss: 0.5746
Epoch 159/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.3817 - val_accuracy: 0.7597 - val_loss: 0.5759
Epoch 160/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.3817 - val_accuracy: 0.7532 - val_loss: 0.5769
Epoch 161/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8241 - loss: 0.3812 - val_accuracy: 0.7532 - val_loss: 0.5774
Epoch 162/200